name = "atelier-velee-payments"
main = "worker.js"
compatibility_date = "2024-01-01"

# Environment variables (these are set in Cloudflare Dashboard)
# The variables below are configured via Dashboard > Workers & Pages > atelier-velee-payments > Settings > Variables
# - ALLOWED_ORIGIN: https://www.ateliervelee.com

# Optional: Custom routes if you want to use your own domain
# [[route]]
# pattern = "yourdomain.com/api/*"
# zone_name = "yourdomain.com"

# Workers configuration
[triggers]
crons = [] 

[vars]
ALLOWED_ORIGIN = "https://www.ateliervelee.com"
MAIL_FROM = "info@ateliervelee.com"
MAIL_FROM_NAME = "Atelier Veleé"
STRIPE_WEBHOOK_SECRET = "whsec_mRt6hISbdHHBDSM2CvVtrqCC2JTKzM4P"

# Observability - Enable logging
[observability.logs]
enabled = true 